version: "3"

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    networks:
      - dokploy-network
    restart: always
    environment:
      - MARIADB_DATABASE=${ENV_MARIADB_DBNAME}
      - MARIADB_USER=${ENV_MARIADB_USER}
      - MARIADB_PASSWORD=${ENV_MARIADB_PASS}
  myapp:
    image: docker.io/bitnami/laravel:latest
    restart: always
    ports:
      - '8000:8000'
    networks:
      - dokploy-network
    environment:
      - LARAVEL_PORT_NUMBER=8000
      - LARAVEL_SKIP_COMPOSER_UPDATE=no
      - LARAVEL_SKIP_DATABASE=no
      - LARAVEL_DATABASE_TYPE=mysql
      - LARAVEL_DATABASE_HOST=mariadb
      - LARAVEL_DATABASE_PORT_NUMBER=3306
      - LARAVEL_DATABASE_NAME=${ENV_MARIADB_DBNAME}
      - LARAVEL_DATABASE_USER=${ENV_MARIADB_USER}
      - LARAVEL_DATABASE_PASSWORD=${ENV_MARIADB_PASS}
    volumes:
      - './:/app'
    depends_on:
      - mariadb
    labels:
      - traefik.enable=true
      - traefik.http.routers.next-app.rule=Host(`laravel.eventskart.in`)
      - traefik.http.routers.next-app.entrypoints=websecure
      - traefik.http.routers.next-app.tls.certResolver=letsencrypt
      - traefik.http.services.next-app.loadbalancer.server.port=8000

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  dokploy-network:
    external: true